name: Build docker

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  build-docker:
    name: Build D-Voting Docker images
    runs-on: ubuntu-22.04
    if: '! github.event.pull_request.draft'
    env:
      DockerTag: ${{ (github.ref == 'refs/heads/main') && 'latest' || github.head_ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfiles/Dockerfile.frontend
          platforms: linux/amd64
          push: true
          tags: ghcr.io/c4dt/d-voting-frontend:${{ env.DockerTag }}
      - name: Build Backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfiles/Dockerfile.backend
          platforms: linux/amd64
          push: true
          tags: ghcr.io/c4dt/d-voting-backend:${{ env.DockerTag }}
      - name: Build D-Voting
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfiles/Dockerfile.dela
          platforms: linux/amd64
          push: true
          tags: ghcr.io/c4dt/d-voting-dela:${{ env.DockerTag }}
