name: Go Scenario Test (with proxy)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ^1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Install crypto util from Dela
        run: |
          git clone https://github.com/dedis/dela.git
          cd dela
          go install ./cli/crypto

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Create a private key
        run: crypto bls signer new --save private.key

      - name: Install dvoting
        run: make build

      - name: Start and setup 5 nodes
        run: ./runSystems.sh -n 5 --docker false --backend false --frontend false --attach false

      - name: Run the scenario Test
        run: go test -timeout 7m -run TestScenario ./integration/...
